### ISSUE TITLE
Admins should be able to make a channel have no links

### ISSUE THREAD

**Issue by DecentralizedDan** [interlock-network/interlock-bouncer#79]
Admins should be able to set a channel to have no links
* This is a common use case for some general interest URLs etc.
* When a user posts a link in that channel, it will delete the message and post `Mods have set this channel to have no links from users.`

Syntax:
  * `!block_links` blocks all links in the current channel
    * `!unblock_links` or similar to allow links again in current channel
  * `!block_links channelname1 channelname2` blocks all links in the named channel(s)
    * `!unblock_links channelname1 channelname2` to allow links again in named channels

Admins should be able to list all nolinks channels via `!block_links_list` or the like

Logging: (in log and security channel as per #75 )
* Making a channel nolinks will be posted in the admin-selected channel as per #75 
* What will be logged is the admin name and the channels made nolink (or allowed to have links again)
* Links that are deleted in nolinks channels will be logged (with username and channel name)

**Comment by jmercouris** [comment]
As of 4545b02 this feature is now almost completed.

The user can now:

`!block_links`
`!unblock links`

missing:

`!block_links_list`.
Logging to the logging channel, that must exist first!

It may not be possible to support the syntax `!block_links channel1 channel2` because I believe there are potential insurmountable challenges. For example, channel names can be changed. What happens if the name is changed while the user is typing? What happens if there exist two channels with the same name (is this possible?)?

**Comment by jmercouris** [comment]
Now that logging to a special channel exists, this task is complete!
